repository:
    path: github.com/warmans/prometheus-aggregate-exporter/cmd
build:
    flags: -a -tags 'netgo static_build'
    ldflags:
      -X main.Version={{.Version}}
tarball:
    files:
crossbuild:
    platforms:
        - linux/amd64
        - linux/386
        - darwin/amd64
        - darwin/386
        - windows/amd64
        - windows/386
        - netbsd/amd64
        - netbsd/386
