name: Docker Image Publish

on:
  push:
    tags: [ v** ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build and pushes image
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: prometheus-aggregate-exporter
          registry: ${{ secrets.DOCKER_REGISTRY }}
          tag_with_ref: true
          push: ${{ startsWith(github.ref, 'refs/tags/') }}
